[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[workspace.dependencies]
hdi = "=0.7.0"
hdk = "=0.6.0"
serde = { version = "1", features = ["derive"] }

[workspace.dependencies.fixture]
path = "dnas/fixture/zomes/coordinator/fixture"

[workspace.dependencies.fixture_integrity]
path = "dnas/fixture/zomes/integrity/fixture"
